// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QUANLYCAYXANH.Data;

#nullable disable

namespace QUANLYCAYXANH.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621033344_AddLichSuChamSoc")]
    partial class AddLichSuChamSoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QUANLYCAYXANH.Models.CayXanh", b =>
                {
                    b.Property<int>("MaCay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCay"));

                    b.Property<string>("LoaiCay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaKhuVuc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTrong")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiPhuTrach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCay");

                    b.HasIndex("MaKhuVuc");

                    b.ToTable("CayXanh");
                });

            modelBuilder.Entity("QUANLYCAYXANH.Models.KhuVuc", b =>
                {
                    b.Property<int>("MaKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuVuc"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhuVuc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhuVuc");

                    b.ToTable("KhuVuc");
                });

            modelBuilder.Entity("QUANLYCAYXANH.Models.LichSuChamSoc", b =>
                {
                    b.Property<int>("MaChamSoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChamSoc"));

                    b.Property<int?>("CayXanhMaCay")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiChamSoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCay")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChamSoc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaChamSoc");

                    b.HasIndex("CayXanhMaCay");

                    b.ToTable("LichSuChamSoc");
                });

            modelBuilder.Entity("QUANLYCAYXANH.Models.CayXanh", b =>
                {
                    b.HasOne("QUANLYCAYXANH.Models.KhuVuc", "KhuVuc")
                        .WithMany("CayXanhs")
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuVuc");
                });

            modelBuilder.Entity("QUANLYCAYXANH.Models.LichSuChamSoc", b =>
                {
                    b.HasOne("QUANLYCAYXANH.Models.CayXanh", "CayXanh")
                        .WithMany("LichSuChamSocs")
                        .HasForeignKey("CayXanhMaCay");

                    b.Navigation("CayXanh");
                });

            modelBuilder.Entity("QUANLYCAYXANH.Models.CayXanh", b =>
                {
                    b.Navigation("LichSuChamSocs");
                });

            modelBuilder.Entity("QUANLYCAYXANH.Models.KhuVuc", b =>
                {
                    b.Navigation("CayXanhs");
                });
#pragma warning restore 612, 618
        }
    }
}
